const languages = [
  { iso_639_1: "bi", english_name: "Bislama" },
  { iso_639_1: "cs", english_name: "Czech" },
  { iso_639_1: "ba", english_name: "Bashkir" },
  { iso_639_1: "ae", english_name: "Avestan" },
  { iso_639_1: "av", english_name: "Avaric" },
  { iso_639_1: "de", english_name: "German" },
  { iso_639_1: "mt", english_name: "Maltese" },
  { iso_639_1: "om", english_name: "Oromo" },
  { iso_639_1: "rm", english_name: "Raeto-Romance" },
  { iso_639_1: "so", english_name: "Somali" },
  { iso_639_1: "ts", english_name: "Tsonga" },
  { iso_639_1: "vi", english_name: "Vietnamese" },
  { iso_639_1: "ig", english_name: "Igbo" },
  { iso_639_1: "it", english_name: "Italian" },
  { iso_639_1: "pl", english_name: "Polish" },
  { iso_639_1: "si", english_name: "Sinhalese" },
  { iso_639_1: "no", english_name: "Norwegian" },
  { iso_639_1: "sk", english_name: "Slovak" },
  { iso_639_1: "uk", english_name: "Ukrainian" },
  { iso_639_1: "en", english_name: "English" },
  { iso_639_1: "ca", english_name: "Catalan" },
  { iso_639_1: "ha", english_name: "Hausa" },
  { iso_639_1: "hu", english_name: "Hungarian" },
  { iso_639_1: "ru", english_name: "Russian" },
  { iso_639_1: "sr", english_name: "Serbian" },
  { iso_639_1: "sv", english_name: "Swedish" },
  { iso_639_1: "fr", english_name: "French" },
  { iso_639_1: "id", english_name: "Indonesian" },
  { iso_639_1: "es", english_name: "Spanish" },
  { iso_639_1: "pt", english_name: "Portuguese" },
  { iso_639_1: "ko", english_name: "Korean" },
  { iso_639_1: "ja", english_name: "Japanese" },
  { iso_639_1: "hi", english_name: "Hindi" },
  { iso_639_1: "zh", english_name: "Chinese" },
  { iso_639_1: "ta", english_name: "Tamil" },
  { iso_639_1: "te", english_name: "Telugu" },
  { iso_639_1: "tr", english_name: "Turkish" },
  { iso_639_1: "ar", english_name: "Arabic" },
  { iso_639_1: "fa", english_name: "Persian" },
  { iso_639_1: "bn", english_name: "Bengali" },
 
];

export default languages;
